#requires -Version 5.1
<#
.SYNOPSIS
    One-shot README splitter used during the v0.7.76 documentation split.
.DESCRIPTION
    Extracts the '## Release History' tail of AzLocal.UpdateManagement/README.md
    into AzLocal.UpdateManagement/docs/release-history.md and replaces the in-README
    section with a short redirect pointer.
.NOTES
    This script is intentionally one-shot; it is NOT idempotent. After it succeeds
    the marker '## Release History' will still exist but the content following it
    will be a 4-line redirect, so re-running this script after the redirect is in
    place would extract the redirect only.
#>

[CmdletBinding()]
param(
    [string]$ReadmePath = (Join-Path $PSScriptRoot '..\README.md'),
    [string]$DocsDir    = (Join-Path $PSScriptRoot '..\docs')
)

$utf8 = [Text.UTF8Encoding]::new($false)
$content = [IO.File]::ReadAllText($ReadmePath, $utf8)
# Normalise CRLF -> LF for the search (we will re-emit LF for the new files,
# which is consistent with the rest of the repo - .gitattributes enforces LF
# on text). Without this the marker '`n## Release History`n' never matches
# when the source file happens to use CRLF.
$contentLf = $content -replace "`r`n", "`n"
$marker = "`n## Release History`n"
$idx = $contentLf.IndexOf($marker)
if ($idx -lt 0) { throw "Marker '## Release History' not found in $ReadmePath" }

$pre = $contentLf.Substring(0, $idx)
$rel = $contentLf.Substring($idx + 1)  # keep '## Release History...'

# Detect already-split state to keep the script safe to re-run accidentally.
if ($rel.Length -lt 500) {
    Write-Host "release-history section is already < 500 chars - looks already-split. No changes made."
    return
}

$relHeader = @'
# AzLocal.UpdateManagement Release History

> **What you will find here:** A chronological record of every released version, in newest-first order. Each entry describes user-visible behaviour changes, bug fixes, and migration steps. The most recent release's full What's-New is also mirrored in the main [README.md](../README.md) under `What's New in v<latest>`.
>
> **For older releases**, this is the canonical reference; the main README intentionally stays slim so the most recent block is easy to find.

---

'@

$relBody = $relHeader + $rel.TrimEnd() + "`n"

if (-not (Test-Path $DocsDir)) { New-Item -ItemType Directory -Path $DocsDir | Out-Null }
$relPath = Join-Path $DocsDir 'release-history.md'
[IO.File]::WriteAllText($relPath, $relBody, $utf8)

$tail = @'

## Release History

The full What's-New history (v0.7.74 and earlier) has moved to [docs/release-history.md](docs/release-history.md).

The most recent release notes for **v0.7.75** stay above under [`What's New in v0.7.75`](#whats-new-in-v0775).

---

_Generated by `AzLocal.UpdateManagement` for Azure Local at-scale fleet updates._
'@

[IO.File]::WriteAllText($ReadmePath, $pre.TrimEnd() + "`n" + $tail, $utf8)

Write-Host "Wrote $relPath ($([IO.File]::ReadAllText($relPath, $utf8).Length) bytes / $((Get-Content $relPath).Length) lines)"
Write-Host "Trimmed $ReadmePath to $((Get-Content $ReadmePath).Length) lines"
